### ISSUE TITLE
Cancel and OK buttons do the same thing on closing.

### ISSUE THREAD

**Issue by VoxelBuster** [4ian/GD#459]
In the GDevelop 5 beta after the "Any unsaved work will be lost" prompt upon clicking the exit button, pressing cancel will close the window anyway.

**Comment by 4ian** [comment]
@VoxelBuster Sorry for answering so long after your initial message. Are you on Windows? I've just tried on macOS and it's working as expected.

**Comment by VoxelBuster** [comment]
Yes this issue is on Windows. If you click the exit button and cancel, the
next time you click it, it will quit the app regardless of if you press Ok
or Cancel.

**Comment by Jose-Moreno** [comment]
@VoxelBuster @4ian Can confirm on Windows 7. Gdevelop 5.0.0-beta34 based on GDevelop.js4.0.97-0-release.

Reproduction steps:

1) Open GDevelop
2) Create either a new project or open an existing project
3) Add or edit any element (for my test I moved an object on screen.
4) Close the app either by pressing X on the window or go to Window > Close
5) Unsaved work message prompt appears. Press Cancel
6) GDevelop quits.

**Comment by 4ian** [comment]
Should hopefully be fixed in beta 36! Let me know if that's not the case.
Closing this now :)

**Comment by Jeje2201** [comment]
Still happen for me, Windows 10, Gd5 Beta 37.

**Comment by Jose-Moreno** [comment]
I can confirm it still happens for me as well when pressing cancel.

OS: Windows 7 Ultimate
GD Version: 5.0.0-beta37

**Comment by Jeje2201** [comment]
And that's a fix, the Beta 39 fix it for windows, it really does a cancel now 😄

**Comment by 4ian** [comment]
🎉
