### ISSUE TITLE
[BUG] Linux: "Add from resource library" dialog not responding to input

### ISSUE THREAD

**Issue by Wend1go** [4ian/GD#97]
If you create a new object and try to choose an image from the resource library the corresponding dialog will open but not respond to any input. Even closing (x) doesn't work, the window only closes if you close the parent "edition of a sprite" window.
As a workaround you can load the images from the "images bank" first but this way you won't see any previews of the pics in the folder tree.

My system:
Linux Mint 17.1 Cinnamon 64Bit

**Comment by victorlevasseur** [comment]
That's indeed a bug. But, in the next version, a preview will be shown in the open picture dialog when adding an image to the image bank.

**Comment by PawBud** [comment]
I think this issue is solved, Shudn't we close it @4ian?

**Comment by 4ian** [comment]
That's a GDevelop 4 issue, it's probably not solved and kept for archiving purpose.

**Comment by PawBud** [comment]
Oops, My bad I am sorry that I pinged u unnecessarily.
